module FnTools.DesignTokens.Tests.Generators

open Hedgehog
open FnTools.DesignTokens


// ─── Primitives ──────────────────────────────────────────────────────────────

let nameChar : Gen<char> =
    Gen.choice [ Gen.alphaNum; Gen.constant '-'; Gen.constant '_' ]

let tokenName : Gen<TokenName> =
    gen {
        let! head = Gen.alpha
        let! rest = Gen.list (Range.linear 0 12) nameChar
        let candidate = string head + System.String(List.toArray rest)
        match TokenName.tryCreate candidate with
        | Ok n -> return n
        | Error _ -> return! Gen.constant (TokenName.tryCreate "fallback" |> function Ok n -> n | _ -> failwith "unreachable")
    }


// ─── Color ───────────────────────────────────────────────────────────────────

let colorSpace : Gen<ColorSpace> =
    Gen.item [
        SRGB; SRGBLinear; DisplayP3; A98RGB; ProPhotoRGB; Rec2020
        HSL; HWB; Lab; LCH; OKLab; OKLCH; XYZD65; XYZD50
    ]

let finiteFloat : Gen<float> =
    Gen.double (Range.linear -1000.0 1000.0)

let unitFloat : Gen<float> =
    Gen.double (Range.linear 0.0 1.0)

let colorComponent : Gen<ColorComponent> =
    Gen.frequency [
        9, finiteFloat |> Gen.map Channel
        1, Gen.constant Missing
    ]

let colorValue : Gen<ColorValue> =
    gen {
        let! cs = colorSpace
        let! a  = colorComponent
        let! b  = colorComponent
        let! c  = colorComponent
        let! alpha = Gen.option unitFloat
        return {
            ColorSpace = cs
            Components = (a, b, c)
            Alpha = alpha
            Hex = None
        }
    }


// ─── Dimension / Duration ────────────────────────────────────────────────────

let dimensionUnit : Gen<DimensionUnit> = Gen.item [ Px; Rem ]

let dimensionValue : Gen<DimensionValue> =
    gen {
        let! v = Gen.double (Range.linear -1000.0 1000.0)
        let! u = dimensionUnit
        return { Value = v; Unit = u }
    }

let durationUnit : Gen<DurationUnit> = Gen.item [ Milliseconds; Seconds ]

let durationValue : Gen<DurationValue> =
    gen {
        let! v = Gen.double (Range.linear 0.0 10000.0)
        let! u = durationUnit
        return { Value = v; Unit = u }
    }


// ─── Font ────────────────────────────────────────────────────────────────────

let fontFamilyValue : Gen<FontFamilyValue> =
    Gen.choice [
        gen { let! s = Gen.string (Range.linear 1 20) Gen.alpha
              return Single s }
        gen { let! n = Gen.int32 (Range.linear 1 4)
              let! ss = Gen.list (Range.singleton n) (Gen.string (Range.linear 1 12) Gen.alpha)
              return Stack ss }
    ]

let fontWeightKeyword : Gen<FontWeightKeyword> =
    Gen.item [
        Thin; Hairline; ExtraLight; UltraLight; Light
        Normal; Regular; Book; Medium
        SemiBold; DemiBold; Bold
        ExtraBold; UltraBold; Black; Heavy
        ExtraBlack; UltraBlack
    ]

let fontWeightValue : Gen<FontWeightValue> =
    Gen.choice [
        Gen.int32 (Range.linear 1 1000) |> Gen.map Numeric
        fontWeightKeyword |> Gen.map Keyword
    ]


// ─── CubicBezier ─────────────────────────────────────────────────────────────

let cubicBezierValue : Gen<CubicBezierValue> =
    gen {
        let! p1x = unitFloat
        let! p1y = finiteFloat
        let! p2x = unitFloat
        let! p2y = finiteFloat
        return { P1x = p1x; P1y = p1y; P2x = p2x; P2y = p2y }
    }


// ─── TokenValue (literal-only — no aliases or composites with refs) ─────────

let simpleTokenValue : Gen<TokenValue> =
    Gen.choice [
        colorValue       |> Gen.map TokenValue.Color
        dimensionValue   |> Gen.map TokenValue.Dimension
        fontFamilyValue  |> Gen.map TokenValue.FontFamily
        fontWeightValue  |> Gen.map TokenValue.FontWeight
        durationValue    |> Gen.map TokenValue.Duration
        cubicBezierValue |> Gen.map TokenValue.CubicBezier
        finiteFloat      |> Gen.map TokenValue.Number
    ]

let inferType (v: TokenValue) : TokenType =
    match v with
    | TokenValue.Color _       -> ColorType
    | TokenValue.Dimension _   -> DimensionType
    | TokenValue.FontFamily _  -> FontFamilyType
    | TokenValue.FontWeight _  -> FontWeightType
    | TokenValue.Duration _    -> DurationType
    | TokenValue.CubicBezier _ -> CubicBezierType
    | TokenValue.Number _      -> NumberType
    | _ -> NumberType  // others not generated by simpleTokenValue

let simpleToken : Gen<Token> =
    gen {
        let! v = simpleTokenValue
        return {
            Value = v
            Type = Some (inferType v)
            Metadata = { Description = None; Deprecated = None; Extensions = [] }
        }
    }


// ─── TokenFile (flat — only direct children, no nested groups) ──────────────

let flatTokenFile : Gen<TokenFile> =
    gen {
        let! n = Gen.int32 (Range.linear 1 10)
        let! tokens =
            Gen.list (Range.singleton n)
                (gen {
                    let! name = tokenName
                    let! tk = simpleToken
                    return name, TokenLeaf tk
                })
        // Deduplicate by name (keep first occurrence) — TokenName uniqueness within a group
        let dedup =
            tokens
            |> List.fold (fun (seen, acc) (n, x) ->
                if Set.contains (TokenName.value n) seen then seen, acc
                else Set.add (TokenName.value n) seen, (n, x) :: acc) (Set.empty, [])
            |> snd
            |> List.rev
        return { Version = V2025_10; Schema = None; Children = dedup }
    }
